name: lrag
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - torchaudio=2.4.1
  - torchvision=0.19.1
  - pip
  - pip:
      - accelerate==1.4.0
      - aiohttp==3.10.11
      - anthropic==0.46.0
      - detectron2==0.6
      - fvcore==0.1.5.post20221221
      - huggingface-hub==0.28.1
      - ipykernel==6.29.5
      - jupyter==1.1.1
      - matplotlib==3.9.4
      - mmcv==2.2.0
      - mmengine==0.10.6
      - numpy==1.26.4
      - opencv-python==4.10.0.84
      - pandas==2.2.3
      - pillow==10.4.0
      - pycocotools==2.0.8
      - roboflow==1.1.54
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - supervision==0.25.1
      - tensorboard==2.18.0
      - tensorflow==2.18.0
      - timm==1.0.15
      - tqdm==4.67.1
      - transformers==4.49.0